/** Generated by itemis CREATE code generator. */

#ifndef VM_REQUIRED_H_
#define VM_REQUIRED_H_

#include "../src/sc_types.h"
#include "VM.h"

#ifdef __cplusplus
extern "C"
{
#endif 

/*! \file
This header defines prototypes for all functions that are required by the state machine implementation.

This state machine makes use of operations declared in the state machines interface or internal scopes. Thus the function prototypes:
- vM_welcome_message
- vM_dispense_product
- vM_return_credit
- vM_select_product
are defined.

These functions will be called during a 'run to completion step' (runCycle) of the statechart. 
There are some constraints that have to be considered for the implementation of these functions:
- never call the statechart API functions from within these functions.
- make sure that the execution time is as short as possible.

*/


extern void vM_welcome_message( VM* handle);
extern void vM_dispense_product( VM* handle, const sc_integer product);
extern void vM_return_credit( VM* handle, const sc_integer credit);
extern void vM_select_product( VM* handle, const sc_integer produc, const sc_integer credit);




#ifdef __cplusplus
}
#endif 

#endif /* VM_REQUIRED_H_ */
